FROM rustlang/rust:nightly AS builder

WORKDIR /app

COPY . .

RUN cargo build --release -p pusher

FROM debian:bookworm-slim

WORKDIR /app

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends openssl ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/pusher ./server

CMD ["./server"]