# 1. Heavy lifting (compiling).
FROM rustlang/rust:nightly AS builder

WORKDIR /app

COPY . .

RUN cargo build --release -p api

# 2. RUNNER STAGE
FROM debian:bookworm-slim

WORKDIR /app

RUN apt-get update -y \
    && apt-get install -y --no-install-recommends openssl ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/api ./server

EXPOSE 3001

CMD ["./server"]