[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
poem = "1.3.59"
serde = { version = "1.0", features = ["derive"] }
store = { path = "../store"}
