[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
poem = { version = "1.3.59", features = ["cookie"] }
serde = { version = "1.0", features = ["derive"] }
dotenvy = "0.15"
store = { path = "../store"}
jsonwebtoken = "9"
